### PR TITLE
Cmake Windows fixes (fixes #145)

### LINKED ISSUE #145: configure script does not use custom jack include directory to detect features
When building qjackctl with a custom jack installation directory, autodetection of jack features (like metadata) fail because jack include path is not used to detect presence of jack headers.

This is a followup of https://github.com/jackaudio/jack2/issues/783.
The resulting qjackctl has no additional features as shown by this screenshot:
image

This issue occurs when building qjackctl as part of a jack release.

### PR DESCRIPTION
**Pull request by amurzeau**
I've kept this PR as multiple commits for easier review. The goal is to make the build using cmake working for use in jack's release scripts (fixes #145).
Here is the whole description of the second batch:

## FindJack/FindPortAudio: show found library instead of include path

When the library is found, find_package_handle_standard_args only show
the first REQUIRED_VAR, so change order to show the library path which is
more interesting than the include path.

## Fix FindPortAudio when using system library

When using system library, pkg-config's PC_PortAudio_INCLUDE_DIRS is empty
because there is no specific include path to use.

As there are only one include path in all cases, just use the one found
using find_path. Only

## Fix detection of CoreAudio

CONFIG_COREAUDIO was never set and thus CoreAudio detection was never
made and always considered unavailable.

## Enable CONFIG_JACK_VERSION by default

This option will be automatically disabled if not supported by Jack anyway.

## Update and fix autodetection of jack functions

Using check_function_exists is discouraged according to CMake documentation,
and check_symbol_exists is prefered.

Fix the detection of CONFIG_JACK_PORT_ALIASES and CONFIG_JACK_VERSION as
check_xxx_exists won't set the variable if it already exists.

## Use all pkg-config libraries as target link libraries

In case of linking to a static version of portaudio, there are additional
libraries for transitive dependencies of portaudio itself.

Also, always add Threads::Threads which portaudio always requires.

------

These commits are merged in daf20679dabfb951a9d7a9a6f369ec306af9adee:

## Use FindJack and FindPortAudio scripts to find dependencies even without pkg-config

This allows building qjackctl on Windows where pkg-config is not available
nor jack's pc file.

## Remove reference to qjackctl.rc and qjackctl.icns which don't exist

This issue was causing a build error on Windows with MinGW.
I've not tested on APPLE, but as images/qjackctl.icns does not exist
either, I expect it to fail too.

## install qjackctl.exe in bin dir

Previously, the executable file was not installed in the install directory,
but in the build directory.

If it is wanted to have qjackctl.exe at the root of the build directory
after a build, one can set RUNTIME_OUTPUT_DIRECTORY instead.

## Fix build on Windows with MSVC

_USE_MATH_DEFINES define is required to make M_PI available.
See https://docs.microsoft.com/fr-fr/cpp/c-runtime-library/math-constants?view=msvc-160

### CODE REVIEW

**Comment by rncbc** [comment]
merged and squashed into develop branch as daf2067 .

thanks

**Comment by amurzeau** [comment]
The current state of that PR is not 100% working according to jack release tests I made over the night, I will need to amend FindPortAudio.cmake (there is missing dependencies to Windows' DLLs required by portaudio static library).

Do you prefer that I just update this PR or that I create a new one ?
(in fact this PR was in draft mode because I was not totally confident about it with Windows, but allowed anyone to see that I was working on it)

**Comment by rncbc** [comment]
you may go on and update on this PR.
though it would be preferable if you rebase to develop branch and not master.
thanks

**Comment by amurzeau** [comment]
ok will do that, thanks

**Comment by amurzeau** [comment]
I've a question about the option `JACK version support` (`CONFIG_JACK_VERSION`), it is disabled by default in CMakeLists.txt
Is there a reason for that or can I :
 - make it on by default
 - if CMake does not find the function jack_get_version_string, automatically disable it

**Comment by amurzeau** [comment]
> 
> 
> you may go on and update on this PR.
> though it would be preferable if you rebase to develop branch and not master.
> thanks

Do you mean rebasing on top of the already merged commit daf20679dabfb951a9d7a9a6f369ec306af9adee ?

**Comment by rncbc** [comment]
> > you may go on and update on this PR.
> > though it would be preferable if you rebase to develop branch and not master.
> > thanks
> 
> Do you mean rebasing on top of the already merged commit [daf2067](https://github.com/rncbc/qjackctl/commit/daf20679dabfb951a9d7a9a6f369ec306af9adee) ?

yes, ofc.

**Comment by amurzeau** [comment]
Done modifications, ready to merge.
I've tested that it builds fine on MacOS, Windows and Linux using system libraries and using custom ones (jack release 'PawPaw')
https://github.com/amurzeau/qjackctl/actions/runs/1148797943
https://github.com/amurzeau/jack2-releases/actions/runs/1148765099

I will make another PR to add the qjackctl github actions, and maybe another one to bundle Qt DLLs in Windows builds artifact.

**Pull request merged**
