### PR TITLE
Revert czech translation for netone/net drivers

### PR DESCRIPTION
**Pull request by sonicpp**
jackd does not know translated name of these drivers

### CODE REVIEW

**Comment by rncbc** [comment]
please add a comment eg. "DO NOT TRANSLATE" to the .ts file.

**Comment by rncbc** [comment]
fixed while on https://github.com/rncbc/qjackctl/commit/a88cd0d. thanks

**Comment by sonicpp** [comment]
I see. So I guess I should close this pull-request

**Comment by trebmuh** [comment]
@rncbc shouldn't this issue be closed?

**Pull request closed without merging**
